version: "3.8"
services: 
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    env_file: 
      - ./env/mongodb.env

  backend:
    build: ./backend
    ports:
      - '80:80'
    volumes: 
      - logs:/usr/src/app/logs
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file: 
      - ./env/backend.env
    depends_on: 
      - mongodb

  # frontend:

volumes:
  data:
  logs: