version: "3.8"
services: 
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: vince
      MONGO_INITDB_ROOT_PASSWORD: secret
  # backend:

  # frontend:

volumes:
  data: